config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  authenticate :user do
    get 'dashboard/index'
    get 'exercises/free' => 'exercises#free'
    get 'exercises/:id' => 'exercises#show'

    get 'exercises/load/:id' => 'exercises#load'
  end
  get 'exercises/demo/:id' => 'exercises#load'
  post '/add_points/:id/:points' => 'users#add_points'
  

  authenticate :admin do
    resources :exercises
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :exercises, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @exercises = Exercise.all
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def free
  end

  def index
  end

  def new
    @new_exercise = Exercise.new 
  end
  
  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save(exercise_params)
      redirect_to edit_exercise_path(@exercise.id)
    else
      render 'new'
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def load 
    @exercise = Exercise.find(params[:id])
    render json: @exercise 
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])

    if @exercise.update(exercise_params)
      redirect_to @exercise
    else
      render 'edit'
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    redirect_to 'exercise/free'
  end

  private
  def exercise_params
    params.require(:exercise).permit(:title, :points, :amount_of_exercises, :json_data)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def add_points
    user = User.find(params[:id])
    user[:points] = user[:points] + Integer(params[:points])
    user.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercise_helper.rb
module ExerciseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.haml
%h1.topbar 
  Eartraining

- @exercises.each do |exercise|
  .row
    .small-12.columns{style: "padding-top: 64px;"}
      %span= "you have #{current_user[:points]} points"
      = link_to exercise do 
        .exercise_link
          %h3= exercise.title
          -#%span points: #{exercise.points}
          .exercise_link__arrow &#8618;

app/views/exercises/edit.html.haml
%h1 Edit a exercise

.row 
  .small-12.columns
    #new_exercise
      %h1 {{exercise.title}}
      <template v-for="(snippet, index) in exercise.json_data">
      <edit_snippet :snippet_data='snippet' :index='index'></edit_snippet>
      </template>
    = form_for @exercise, url: {action: "update"}, method: 'patch' do |f|
      = f.text_field :title
      = f.text_area :json_data, size: "60x12"
      = f.text_field :points
      = f.text_field :amount_of_exercises
      = f.submit "Update exercise"

app/views/exercises/free.html.haml
%body
  = render 'exercises/shared/sidebar'
  #exercise
    %h1.topbar {{exercise.title}}
    .exercise_container
      .row 
        .small-12.columns
          <h1 v-if="exercise_amount < 1">DONE!</h1>
          <h3 v-if="exercise_amount < 1">Points: {{all_points}} </h3>
          <template v-for="(snippet, index) in exercise.json_data">
          <snippet v-on:add_points='add_points' :snippet_data='snippet' :index='index' v-on:delete="delete_snippet(index)"></snippet>
          </template>

  :javascript

app/views/exercises/new.html.haml
.row
  .small-12.columns
    %h1 New Exercise
    -#%h1= Exercise.last.id + 1

.row
  .small-12.columns
.row 
  .small-12.columns
    #new_exercise
      .row
        <template v-for="(snippet, index) in exercise.json_data">
        <edit_snippet :snippet_data='snippet' :index='index' v-on:delete="delete_snippet(index)"></edit_snippet>
        </template>
        <create_snippet :exercise='exercise'></new_snippet>
      .row
        = form_for @new_exercise, url: {action: "create"} do |f|
          = f.label :title, "Name of exercise"
          = f.text_field :title
          <textarea name='exercise[json_data]' id='exercise_json_data' :v-bind="exercise.json_data">{{exercise.json_data}}</textarea>
          -#= f.text_area :json_data, size: "60x12"

          = f.label :points, "Amount of points awarded for clearing exercise"
          = f.text_field :points
          = f.label :amount_of_exercises, "Amount of exercises (snippets) in exercise"
          = f.text_field :amount_of_exercises
          = f.submit "Create exercise"

app/views/exercises/shared/_sidebar.html.haml
= link_to dashboard_index_url do
  .sidebar-menu-button#sidebar-menu-button
    &#8592;
.sidebar.hide#sidebar-menu
  .row
    .small-columns-12
      %h3.sidebar__title Freeform Exercise
      %ul.breadcrumbs
        %li.breadcrumbs__item Lesson 1
        %li.breadcrumbs__item Lesson 2
        %li.breadcrumbs__item Lesson 3

app/views/exercises/show.html.haml
- content_for :javascript_files do
  = javascript_include_tag :exercise

%body
  = render 'exercises/shared/sidebar'
  #exercise
    %h1.topbar 
      {{exercise.title}}
      .topbar__user{id: current_user.id}
    .exercise_container
      .row 
        .small-12.columns
          <div v-cloak>
          <h1 class='exercise__message' v-if="exercise_amount < 1">Good job!</h1>
          <h3 class='exercise__message' v-if="exercise_amount < 1">you earned: {{all_points}} points</h3>
          <a class='exercise__back_link'href='/dashboard/index' v-if="exercise_amount < 1">&#8592; back</a>
          <template v-for="(snippet, index) in exercise.json_data">
          <snippet v-on:add_points='add_points' :snippet_data='snippet' :index='index' v-on:delete="delete_snippet(index)"></snippet>
          </template>
          </div>

  :javascript

app/views/home/index.html.haml
- content_for :javascript_files do
  = javascript_include_tag :home
.hero
  .row
    .small-12.medium-10.medium-centered.columns
      %h1.hero__header Ear Training
  .row
    .small-12.medium-10.medium-centered.columns
      %h4.hero__subheader Learn music theory by listening
  .row
    .small-12.medium-4.medium-centered.columns
      = link_to new_user_registration_url do
        .button.register_button Sign up
    .small-12.medium-4.medium-centered.columns
      = link_to new_user_session_url do
        .button.register_button Log in

.feature_grid
  .row.align-center
    .small-4.columns.feature_block
      .feature_block__image.feature_block__image--lessons
      .feature_block__header
        Lessons
      .feature_block__subheader
        that teach you music theory
    .small-4.columns.feature_block
      .feature_block__image.feature_block__image--exercises
      .feature_block__header
        Exercises 
      .feature_block__subheader
        that help you learn
    .small-4.columns.feature_block
      .feature_block__image.feature_block__image--training
      .feature_block__header
        Training 
      .feature_block__subheader
        that trains your ears
        
.feature_showcase
  .row
    .small-12.columns
      .feature_showcase__img.feature_showcase__img--product
  .row
    .small-12.columns
      %h3.feature_showcase__header Sign up now to get access to the alpha! 

.demo
  #exercise
    %h1.topbar 
      Demo of an exercise
    .exercise_container
      .row 
        .small-12.columns
          <div v-cloak>
          <h1 class='exercise__message' v-if="exercise_amount < 1">Good job!</h1>
          <h3 class='exercise__message' v-if="exercise_amount < 1">you earned: {{all_points}} points</h3>
          <a class='exercise__back_link'href='/dashboard/index' v-if="exercise_amount < 1">&#8592; back</a>
          <template v-for="(snippet, index) in exercise.json_data">
          <snippet v-on:add_points='add_points' :snippet_data='snippet' :index='index' v-on:delete="delete_snippet(index)"></snippet>
          </template>
          </div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Eartraining
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :javascript_files
  %body
    -#%p.alert-box.notice= notice
    -#%p.alert-box.alert= alert
    = yield